Jun.
kai5z/Chladni-patterns pull request #7
Opened 2022-12-18 03:51 UTC by juninagaki1975

Arranged some parts.

2022-12-18 09:06 UTC, kai5z requested changes
Hi, thanks! Are you aware that these changes would be merged to the main repository?

If so: To me it looks like these would likely break the code? Also some loops that have no function? I won't merge this...

2022-12-18 12:55 UTC, juninagaki1975 commented
Thank you for your reply.
> Also some loops that have no function?
Is this mentioned about clamped center point?

2022-12-18 14:33 UTC, juninagaki1975 commented on sweep.py
> +    return Matrix([[dNNx[ix],-dNNy[ix],0],[dNNy[ix],0,-dNNx[ix]]])
Components of B matrix must be derivatives all?
Replace NN with dNNx or dNNy based on some textbooks.

2022-12-18 14:34 UTC, juninagaki1975 commented on sweep.py
> +    for i in range(0,4):
According to convention, swapped i and j.
(Not so affect on main work)

2022-12-18 14:35 UTC, juninagaki1975 commented on sweep.py
> +for j in range(0,4):
Added j loop on outer nest.
But I think it has worked without trouble when it was not modified.

2022-12-18 14:37 UTC, juninagaki1975 commented on sweep.py
> -K = np.delete(K, ix, axis=0)
Is this work like as deallocate in fortran?
I comment outed on my workspace but it must keep work on if you need these treatment...

2022-12-18 14:40 UTC, juninagaki1975 commented on sweep.py
> +ix = range(ix_i,ix_i+3)
The location external force applying.
When we mistake the choich of these three components in Force,
Chladni patterns may break symmtery.
(Is the order of Force components are u,v,w? It's not like...)

2022-12-18 14:47 UTC, kai5z commented
Hi Jun. Could you please provide a picture / outtake on where this is
opened up in the textbook? Or how you derived this result using e.g.
Galerkin. Looking then at the shear force part of the stiffness matrix. To
be honest I do not directly remember how I calculated this since it was
almost 10 years ago.

On Sun, Dec 18, 2022 at 4:33 PM Jun ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In sweep.py
> <https://github.com/kai5z/Chladni-patterns/pull/7#discussion_r1051613830>:
>
> > @@ -59,7 +59,7 @@
>  def Bb(ix):
>      return Matrix([[0,dNNx[ix],0],[0,0,dNNy[ix]],[0,dNNy[ix],dNNx[ix]]])
>  def Bs(ix):
> -    return Matrix([[dNNx[ix],-NN[ix],0],[dNNy[ix],0,-NN[ix]]])
> +    return Matrix([[dNNx[ix],-dNNy[ix],0],[dNNy[ix],0,-dNNx[ix]]])
>
> Components of B matrix must be derivatives all?
> Replace NN with dNNx or dNNy based on some textbooks.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kai5z/Chladni-patterns/pull/7#pullrequestreview-1222037502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJBNK7UNEN7MRYIVUYMTKTWN4OD7ANCNFSM6AAAAAATCJOD5Y>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-12-18 14:55 UTC, juninagaki1975 reviewed
I added motivations on all revised points.
When you feel not suitable, please reject my requests.
But I would like you to allow me to keep utiolizing your code for my research.
In May I have Japan applied Physics meeting.
I state your name as original author but for troubles I must take in charge.

2022-12-18 14:55 UTC, juninagaki1975 commented on sweep.py
> -    #Add back zeros (boundaries)
By addition of these clamping point, total shape of dispolacement matrix seems like disaligned.
To Kai: When we arrange and solve this disalignment, I think I can apply clamp point?
(Sorry, I am utilizing this code withou clamp point)

2022-12-18 14:55 UTC, juninagaki1975 commented on sweep.py
> +    eplo = eplo_p[0::3]
Because I removed clamped point, I employed original displacement vector directly.

2022-12-18 14:55 UTC, juninagaki1975 commented on sweep.py
> +# Jun for debug use.
When debuggin it looks clear. so just use no-interpolate mode.

2022-12-18 15:18 UTC, juninagaki1975 commented
Because this is midnight in Japan, I would like to make answer to you tomorrow.
I am beginner for FEM so I would like to inform anything honestly.
Some part may be mixed with my own thought unclearly.

2022-12-18 16:21 UTC, kai5z commented
Hi Jun

Please dont worry, I regrettably have very little time to use on this also
so I might not always reply quickly. I think if you can reply to the
questions I asked it should also be very useful for you.

-Kai

On Sun 18. Dec 2022 at 17.19, Jun ***@***.***> wrote:

> Because this is midnight in Japan, I would like to make answer to you
> tomorrow.
> I am beginner for FEM so I would like to inform anything honestly.
> Some part may be mixed with my own thought unclearly.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/kai5z/Chladni-patterns/pull/7#issuecomment-1356820570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJBNK2ODM374HQERSWVQWLWN4TOJANCNFSM6AAAAAATCJOD5Y>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-12-19 04:56 UTC, juninagaki1975 commented
I awared my lack of courtsey, I would like to build up good communication from the begininng again.
I close this pull request and open an issue what I met on the original sweep.py.

2022-12-19 04:59 UTC, closed without merging